apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pedrolb777
  name: pedrolb777
spec:
  ports:
  - name: 9091-80
    port: 9091
    protocol: TCP
    targetPort: 80
  selector:
    app: pedro-finalapp # label of pods
  type: NodePort
status:
  loadBalancer: {}
